import { Callout, CodeBlock, InlineCode } from '@/components/api-docs';

export function RouterSetupGuide() {
  return <div className="space-y-6">
    <Callout title="Already have a working console?">If your administrator supplied a console URL and login, sign in there and skip installation. The instructions below are for the person running the router, not every gsai computer owner.</Callout>
    <h3 className="text-lg font-semibold">1. Get the project and prerequisites</h3>
    <p className="text-sm leading-7 text-muted-foreground">Use the current router checkout supplied by your maintainer. Its root must contain llm-gateway-console/backend and llm-gateway-console/frontend. A gsai CLI checkout is a different project. These examples use Python 3.12 and Node.js 22; install them and Git first if missing. See <a className="underline" href="https://www.python.org/downloads/">Python downloads</a> and <a className="underline" href="https://nodejs.org/en/download">Node.js downloads</a>. Node.js includes npm. The frontend uses Vite 6; see its <a className="underline" href="https://v6.vite.dev/guide/">runtime requirements</a>.</p>
    <CodeBlock label="macOS / Linux — check prerequisites" value={'python3.12 --version\nnode --version\nnpm --version\ngit --version'} />
    <CodeBlock label="Windows PowerShell — check prerequisites" value={'py -3.12 --version\nnode --version\nnpm.cmd --version\ngit --version'} />
    <p className="text-sm leading-7 text-muted-foreground">If a command is missing, install that prerequisite and reopen the terminal. Use Python 3.12 for the virtual environment below. This is a source-development setup, not a packaged production installer. Dependency downloads can be large; an installation error must be resolved before startup.</p>
    <h3 className="text-lg font-semibold">2. Prepare the backend (terminal A)</h3>
    <p className="text-sm leading-7 text-muted-foreground">Open a terminal in the router repository root. Run only your operating system’s block. If already inside backend, skip the cd line. Keep an existing .venv and .env; do not overwrite your secrets or database.</p>
    <CodeBlock label="macOS / Linux — first installation" value={'cd llm-gateway-console/backend\npython3.12 -m venv .venv\nsource .venv/bin/activate\npython -m pip install -r requirements.txt\nif [ ! -f .env ]; then\n  cp .env.example .env\nfi\npython -c "import secrets; print(secrets.token_urlsafe(48))"'} />
    <CodeBlock label="Windows PowerShell — first installation" value={'cd llm-gateway-console/backend\npy -3.12 -m venv .venv\n.\\.venv\\Scripts\\python.exe -m pip install -r requirements.txt\nif (-not (Test-Path .env)) { Copy-Item .env.example .env }\n.\\.venv\\Scripts\\python.exe -c "import secrets; print(secrets.token_urlsafe(48))"'} />
    <p className="text-sm leading-7 text-muted-foreground">Open backend/.env in your editor. Set ADMIN_USERNAME to your chosen login name, ADMIN_PASSWORD to a strong password you save securely, and ADMIN_SESSION_SECRET to the random value just printed. Replace the example change-this values; do not leave placeholders. Keep the other defaults for this same-computer test. Never commit .env or share its contents.</p>
    <CodeBlock label="Start backend — macOS / Linux (terminal A, in backend)" value={'source .venv/bin/activate\npython -m uvicorn app.main:app --reload --host 127.0.0.1 --port 8000'} />
    <CodeBlock label="Start backend — Windows (terminal A, in backend)" value={'.\\.venv\\Scripts\\python.exe -m uvicorn app.main:app --reload --host 127.0.0.1 --port 8000'} />
    <Callout title="Check: backend started">Leave terminal A running. Expect “Application startup complete” and http://127.0.0.1:8000. Open http://127.0.0.1:8000/health in a browser: it should return status ok. This checks the router process, not Ollama or an answer model. If port 8000 is occupied, identify the existing service instead of starting a duplicate.</Callout>
    <h3 className="text-lg font-semibold">3. Start the website (terminal B)</h3>
    <p className="text-sm leading-7 text-muted-foreground">Open a second terminal in the same repository root; do not stop the backend. If already inside frontend, skip cd. npm install is needed initially or after dependency changes, not every launch.</p>
    <CodeBlock label="macOS / Linux — frontend" value={'cd llm-gateway-console/frontend\nnpm install\nVITE_API_BASE_URL=http://127.0.0.1:8000 VITE_PUBLIC_GATEWAY_URL=http://127.0.0.1:8000 npm run dev -- --host 127.0.0.1 --port 5173 --strictPort'} />
    <CodeBlock label="Windows PowerShell — frontend" value={'cd llm-gateway-console/frontend\nnpm.cmd install\n$env:VITE_API_BASE_URL = "http://127.0.0.1:8000"\n$env:VITE_PUBLIC_GATEWAY_URL = "http://127.0.0.1:8000"\nnpm.cmd run dev -- --host 127.0.0.1 --port 5173 --strictPort'} />
    <h3 className="text-lg font-semibold">4. Sign in for the first time</h3>
    <p className="text-sm leading-7 text-muted-foreground">Open <InlineCode>http://127.0.0.1:5173</InlineCode>. Use exactly the ADMIN_USERNAME and ADMIN_PASSWORD you saved in backend/.env—not your Cloudflare login, node token or API key. Successful login opens Overview. Zero registered nodes is normal on first use. Go to Local testing next.</p>
    <Callout title="Check: first login">Both terminals remain running, Overview loads, and the workspace shows http://127.0.0.1:8000. Failed login: verify your .env and restart backend after edits. Network/CORS error: check backend startup and ADMIN_CORS_ORIGINS includes http://127.0.0.1:5173. Do not solve a login problem by disabling authentication.</Callout>
    <p className="text-sm leading-7 text-muted-foreground">On later launches, run the backend start block in backend and the frontend run command in frontend. Ctrl+C stops each development server; it does not remove models or the saved database. Restart backend after .env changes and frontend after VITE_ changes.</p>
  </div>;
}
